config/routes.rb
Rails.application.routes.draw do

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox

  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent

  get "mailbox/trash"  => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  
  get '/users/index' => 'users#index'

  devise_for :users, :path => 'accounts'

  get 'users/edit'

  get 'users/update'

  get 'users/show'

  get 'users/new'

  get 'users/edit'

  get 'users/list'

  get 'users/update'

  get 'users/show'

  get 'widgets/help'

  get 'widgets/help'

  get 'pages/about'

  get 'pages/about'

  resources :posts
  resources :comments

  resources :users

  get '/myprojects' => 'posts#list'

  get '/settings' => 'users#edit'

  get 'profile' => 'users#show'
  resources :widgets

  patch 'update' => 'users#up'

  get 'posts' => 'posts#new'
  post '/posts' => 'posts#create'

  authenticated :user do
    root to: 'posts#index'
  end
  unauthenticated :user do
    root to: 'welcome#index' , as: 'home'
  end

  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
      get "like", to: "posts#upvote"
      get "dislike", to: "posts#downvote"
    end
    resources :comments
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  acts_as_votable

  validates_presence_of :post_content
  validates_presence_of :post_title
  validates_presence_of :user

  def self.search(search)
    where("post_content ILIKE ? OR post_title ILIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    if params[:search]
      @posts = Post.search(params[:search]).order("created_at DESC")
    else
      @posts = Post.all.order("created_at DESC")
    end
  end

  def list
    @posts = current_user.posts
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to posts_path
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    redirect_to @posts
  end

 # def index(set)
 #     @posts = current_user.posts
 # end

  # def current_user_index
  #   @posts = current_user.posts
  # end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = Comment.where(post_id: @post).order("created_at DESC")
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params) do |post|
    end

    @post.user = current_user
    # @post.user = current_user
    # respond_to do |format|
    #   if @post.save
    #     format.html { redirect_to @post, notice: 'Post was successfully created.' }
    #     format.json { render :show, status: :created, location: @post }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @post.errors, status: :unprocessable_entity }
    #   end
    # end
    if @post.save
        redirect_to posts_url
    else
        redirect_to root_path, notice: @post.errors.full_messages.first
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:post_title, :post_content, :user_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Project %><br>
    <%= f.text_field :post_title %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :post_content %>
  </div>
  <!-- <% @post.user = current_user %>-->

    <!-- <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</div>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posted Projects</h1>

<table>
  <thead>
    <tr>
      <th>Post title</th>
      <th>Post content</th>
      <th>User Name</th>
      <th>Like here</th>
      <th># of likes</th>

      <th colspan="8"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.post_title, post_path(post)%></td>
        <td><%= post.post_content %></td>
        <td><%= post.user.name %></td>
        <td><%= link_to like_post_path(post), method: :put do%> Interested?<% end %></td>
        <!---like_post_path(post) -->
        <td><%= pluralize(post.get_upvotes.size, 'like') %></td>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path([:user_id]) %>

app/views/posts/list.html.erb
<p id="notice"><%= notice %></p>

<h1>My Projects</h1>

<table>
  <thead>
    <tr>
      <th>Post title</th>
      <th>Post content</th>


      <th colspan="8"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.post_title %></td>
        <td><%= post.post_content %></td>
        
        <td><%= link_to 'Show', post %></td>
        <!-- <td><%= link_to 'Edit', post,  method: :edit %></td> -->
        <td><%= link_to 'Edit', edit_post_path(post) %></td>

        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path([:user_id]) %>

app/views/posts/new.html.erb
<h1>Project Posting</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post title:</strong>
  <%= @post.post_title %>
</p>

<p>
  <strong>Post content:</strong>
  <%= @post.post_content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= render 'comments/comment' %>

<!-- <%= link_to 'Edit',edit_post_path(@post) %> | --> 
<%= link_to 'Back', posts_path %>