config/routes.rb
Rails.application.routes.draw do

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox

  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent

  get "mailbox/trash"  => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  
  get '/users/index' => 'users#index'

  devise_for :users, :path => 'accounts'

  get 'users/edit'

  get 'users/update'

  get 'users/show'

  get 'users/new'

  get 'users/edit'

  get 'users/list'

  get 'users/update'

  get 'users/show'

  get 'widgets/help'

  get 'widgets/help'

  get 'pages/about'

  get 'pages/about'

  resources :posts
  resources :comments

  resources :users

  get '/myprojects' => 'posts#list'

  get '/settings' => 'users#edit'

  get 'profile' => 'users#show'
  resources :widgets

  patch 'update' => 'users#up'

  get 'posts' => 'posts#new'
  post '/posts' => 'posts#create'

  authenticated :user do
    root to: 'posts#index'
  end
  unauthenticated :user do
    root to: 'welcome#index' , as: 'home'
  end

  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
      get "like", to: "posts#upvote"
      get "dislike", to: "posts#downvote"
    end
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
end

app/models/identity.rb
class Identity < ActiveRecord::Base
   belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  acts_as_votable

  validates_presence_of :post_content
  validates_presence_of :post_title
  validates_presence_of :user

  def self.search(search)
    where("post_content ILIKE ? OR post_title ILIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter

  has_many :posts
  has_many :comments
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "http://www.finearttips.com/wp-content/uploads/2010/05/avatar.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  acts_as_messageable
  
  def mailboxer_name
    self.name
  end
  
  def mailboxer_email(object)
    self.email
  end

  geocoded_by :city
  after_validation :geocode

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end

  def profile
  end
end

app/controllers/like_controller.rb
class LikesController < ApplicationController
  before_action :find_likeable
  before_action :authenticate_user!
  respond_to :js

  def create
    @likeable.liked_by current_user
  end

  def destroy
    @likeable.disliked_by current_user
  end

  private
  def find_likeable
    @likeable_type = params[:likeable_type].classify
    @likeable = @likeable_type.constantize.find(params[:likeable_id])
  end
end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
  
  before_action :authenticate_user!
  def inbox
    @inbox = mailbox.inbox
    @active = :inbox
  end

  def sent
    @sent = mailbox.sentbox
    @active = :sent
  end

  def trash
    @trash = mailbox.trash
    @active = :trash
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
  def profile
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    if params[:search]
      @posts = Post.search(params[:search]).order("created_at DESC")
    else
      @posts = Post.all.order("created_at DESC")
    end
  end

  def list
    @posts = current_user.posts
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to posts_path
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    redirect_to @posts
  end

 # def index(set)
 #     @posts = current_user.posts
 # end

  # def current_user_index
  #   @posts = current_user.posts
  # end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = Comment.where(post_id: @post).order("created_at DESC")
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params) do |post|
    end

    @post.user = current_user
    # @post.user = current_user
    # respond_to do |format|
    #   if @post.save
    #     format.html { redirect_to @post, notice: 'Post was successfully created.' }
    #     format.json { render :show, status: :created, location: @post }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @post.errors, status: :unprocessable_entity }
    #   end
    # end
    if @post.save
        redirect_to posts_url
    else
        redirect_to root_path, notice: @post.errors.full_messages.first
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:post_title, :post_content, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!


  def edit
    @user = current_user
  end

  def index
    @users = User.all
    if current_user.admin?
          @posts = User.all
    end
    @map_hash = Gmaps4rails.build_markers(@users) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      marker.infowindow user.name
    end
  end

  def update
    @user = User.find(current_user.id)
    if @user.update_attributes(user_params)
      bypass_sign_in(@user)
      redirect_to '/'
    else
      render 'edit'
    end
  end

  def show
  end


  def new
    @user = User.new
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation, :image, :name, :about, :city, :latitude, :longitude)
  end

end

# Now able to identify administrators:
#
# if current_user.admin?
#   # do something
# end
# If the page could potentially not have a current_user set then:
#
# if current_user.try(:admin?)
#   # do something
# end
# With the above way if current_user were nil, then it would still work without raising an undefined method admin? for nil:NilClass exception.
#
# The code below can be used to grant admin status to the current user.
#
# current_user.update_attribute :admin, true

app/helpers/application_helper.rb
module ApplicationHelper
  def belongs_to_user?(resource)
    resource.user == current_user
  end
  
  def active_page(active_page)
    @active == active_page ? "active" : ""
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
    def unread_messages_count
    # how to get the number of unread messages for the current user
    # using mailboxer
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def is_current_user?(user)
    user == current_user
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>STARTNOW</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag  '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag  '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js' %>
  <% javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
  
  
</head>
<body>
          <!-- <div class= "navbar"> -->
            <div class="container-fluid">
                <ul class="nav navbar-nav navbar-left">
                  <li><img src="http://startupsuccess.ca/wp-content/uploads/2014/09/Now-Startup-Logo-Clear-Blue-Smaller1.png" alt="StartNow" style="width:50px;height:50px;"></img></li>
                    <li style="margin-left:5px;"><% if user_signed_in? %>
                      <div class="form-group">
                        <%= form_tag(posts_path, :method => "get", id: "search-form") do %>
                        <%= text_field_tag :search, params[:search], placeholder: "Search Projects" %>
                        <%= submit_tag "Search", :name => nil %>
                        <% end %>
                      </div><% else %><% end %>

                    </li>
                 </ul>

                <ul class="nav navbar-nav navbar-right">

                  <% if user_signed_in? %>
                      <li class="active"> <%= link_to 'Home', posts_path %></li>
                      <li> <%= link_to 'Profile', profile_path %></li>
                      <li> <%= link_to 'My Projects', myprojects_path %></li>
                      <li> <%= link_to 'Inbox', mailbox_inbox_path %></li>
                      <li> <%= link_to 'CollaboMap', '/users/index' %></li>
                      <li> <%= link_to 'Settings', settings_path %></li>
                      <li><%= link_to 'Sign out', destroy_user_session_path, method: :get %></li>

                  <% else %>
                      <li class="active"> <%= link_to 'Home', root_path %></li>
                      <li><%= link_to 'About', pages_about_path %></li>
                      <li><%= link_to 'Register', new_user_registration_path %> </li>
                      <li> <%= link_to 'Sign in', new_user_session_path %> </li>
                  <% end %>
                </ul>
              </div>

            <!-- </div> -->

            <% if notice %>
             <p class="notice"><%= notice %></p>
           <% end %>

           <% if alert %>
             <p class="alert"><%= alert %></p>
           <% end %>

            <%= yield %>



</body>
</html>

app/views/pages/about.html.erb
</div>

    <div class="jumbotron">
      <div class="container">
        <h1>STARTNOW</h1>
        <p>Where Collaboration Begins</p>
      </div>
    </div>
    <div class="posters">
        <div class="container">
            <h2>Why Start Later When You Can START NOW?</h2>
            <div class="row">
                <div class="col-md-4">
                    <div class="thumbnail">
                        <img src="https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/14955953_10202455122895857_4720710582512918774_n.jpg?oh=d4b8294e5336d8b3b4780a23de7b2753&oe=588DBB9B">
                        <p><a href="#">See the team. Giovanni, David, Joanna, Manpreet (left to right)</a></p>
                    </div>

                </div>
                <div class="col-md-4">
                    <div class="thumbnail">
                    <img src="https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/1044928_10201588717556265_7013929658822700952_n.jpg?oh=02a78e3e388d2fc897eb2db72f3bc859&oe=5894D999">
                    <p> <a href = "https://arcane-shelf-86139.herokuapp.com" >The Team deployed their app using Heroku, see here</a> </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="thumbnail">
                    <img src="https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/1044928_10201588717556265_7013929658822700952_n.jpg?oh=02a78e3e388d2fc897eb2db72f3bc859&oe=5894D999">
                    <p> <a href = "https://github.com/Collabotech/StartNow" >The team copped first place for most Innovative Idea at Collabohacks, See Github for StartNow </a> </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="lm">
	  <div class="container">
		<div class="row">

      <div class="col-md-4">
			<h3>Search</h3>
			<p>Join hundreds of other postings</p>
			  <p>
          <% if user_signed_in? %>
          <%= link_to 'See how others have done it', posts_path %></p>
            <% else %>
            <p>  <%= link_to 'See how others have done itt', new_user_session_path %></p>
              <!-- ink_to 'Post a new project', new_user_session_path %> -->
  		          <% end %>
	      </div>

		  <div class="col-md-4">
			<h3>Post</h3>
			<p> Get partners to being on your mission whether it be startup, a project or even an idea</p>
      <p><% if user_signed_in? %>
            <%= link_to 'Post a new project', new_user_post_path(:user_id) %></p>
        <% else %>
            <%= link_to 'Post a new project', new_user_session_path %>
		  <% end %>

    </div>

			<h3>Collaborate</h3>
			<p>Where Collaboration Begins. Why Start later when you can StartNow?</p>
			<p>
         <% if user_signed_in? %>
        <%= link_to 'See Many Postings', posts_path %></p>
        <% else %>
          <%= link_to 'See Many Postings', new_user_session_path %>
		        <% end %>
        </p>
        <br>
		  </div>
   </div>

 <div style="margin-left:25px;">
        <h4> Contact Us: </h4>
          <p>
          Address : 8888 University Drive <br>
          Tel #: 605-555-3795
    	   </P>
	</div>

  <br>
     <div class="footer"> <h5 style="text-align:center;">Collabotech 2018 Inc. (c)</h5></div>

  </body>
</html>

app/views/pages/index.html.erb
<div class="jumbatron">
  <h1>Welcome to StartNow!</h1>

</div>

app/views/pages/profile.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <div class="well">
      <h3>Edit Profile</h3>
      <%= form_for User.new do |f| %>
        <div class="form-group">
          <%= f.label :cover %>
          <br>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, placeholder: 'Full Name', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :about %>
          <%= f.text_area :about, placeholder: 'About', class: 'form-control' %>





        <div class="actions">
          <%= submit_tag 'Update', class: 'btn btn-primary' %>
        </div


      <% end %>
    </div>

  </div>
</div>

app/views/pages/show.html.erb
<div class="row">
    <div class="col-md-6 col md-offset-3">
      <h1>Profile</h1>

      <% user = current_user %>

      <table class="table">
          <tr>
              <th>Name</th>
              <td><%= user.name %></td>
          </tr>
          <tr>
              <th>Email</th>
              <td><%= user.email %></td>
          </tr>



      </table>
    </div>
</div>

app/views/welcome/index.erb
<p> Welcome to Startnow </p>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>WELCOME TO STARTNOW</title>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

  <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>


  <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">



  <!-- <%= stylesheet_link_tag 'welcome', media: 'all', 'data-turbolinks-track' => true %> -->


</head>
    <body data-spy="scroll" data-offset="20" data-target="#navbar">
    <!-- Nav Menu Section -->
    <!-- <div class="logo-menu">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation" data-spy="affix" data-offset-top="50">
      <div class="container">

        <div class="navbar-header col-md-3">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#home"><i class="fa fa-briefcase"></i> Corporal</a>
        </div>

        <div class="collapse navbar-collapse" id="navbar">
                            <ul class="nav navbar-nav col-md-9 pull-right">
                            <li class="active"><a href="#hero-area"><i class="fa fa-home"></i> Home</a></li>
                            <li><a href="#services"><i class="fa fa-cogs"></i> Services</a></li>
                            <li><a href="#portfolio"><i class="fa fa-flask"></i> Portfolio</a></li>
                            <li><a href="#clients"><i class="fa fa-puzzle-piece"></i> Clients</a></li>
                            <li><a href="#about"><i class="fa fa-info"></i> About</a></li>
                            <li><a href="#contact"><i class="fa fa-envelope"></i> Contact</a></li>
                            </ul>
        </div>
      </div>
    </nav>
    </div> -->
<!-- Nav Menu Section End -->

<!-- Hero Area Section -->

<section id="hero-area">
<div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 class="title">STARTNOW</h1>
        <h2 class="subtitle">Why start later when you can <i><u>START NOW</u></i>!</h2>
        <img class="col-md-6 col-sm-6 col-xs-12 animated fadeInLeft" src="https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/14955953_10202455122895857_4720710582512918774_n.jpg?oh=d4b8294e5336d8b3b4780a23de7b2753&oe=588DBB9B" alt="">
        <div class="col-md-6 col-sm-6 col-xs-12 animated fadeInRight delay-0-5">
            <p>Register or Sign Up to kickstart your awesome collaborative experience</p>
            <button><%= link_to 'Register', new_user_registration_path %></button>
            <button> <%= link_to 'Sign in', new_user_session_path %></button>

        </div>
      </div>
    </div>

</div>
</div>
</section>
</body>
</html>